language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq libyajl-dev libxml2-dev libxqilla-dev
  - sudo apt-get install libarmadillo-dev libarmadillo4
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq clang-3.5; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.5" CC="clang-3.5"; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - $CXX --version
script: make
