language: cpp
compiler:
  - gcc
  - clang
env:
  # - if [ "$CXX" = "clang++" ]; then export config ; fi
  - if [ "$CXX" = "g++" ]; then export CONFIG="max"; fi
before_install:
  # gcc 4.9
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  # clang 3.5
  # - sudo add-apt-repository -y ppa:h-rayflood/llvm
  - sudo add-apt-repository -y "deb http://us.archive.ubuntu.com/ubuntu trusty main universe"
  - sudo add-apt-repository -y "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main"
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq libyajl-dev libxml2-dev libxqilla-dev
  - sudo apt-get install libarmadillo-dev libarmadillo4
  - sudo apt-get install libnlopt-dev libnlopt0
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq clang-3.5; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.5" CC="clang-3.5"; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - $CXX --version
script: make
